redshift_common: &redshift_common
  host: aleph-public.cdiwpivlvfxt.us-east-1.rds.amazonaws.com
  database: aleph_public
  port: 5432

production:
  <<: *redshift_common

staging:
  <<: *redshift_common

test:
  <<: *redshift_common

development:
  <<: *redshift_common
